export const protected_routes = [
  { path: "dashboard", permission_name: null },
  {
    path: "learning_segment",
    permission_name: "training_solutions_management",
  },
  { path: "activity_logs", permission_name: "activity_log_management" },
  {
    path: "expert_trainer_profiles",
    permission_name: "training_solutions_management",
  },
  { path: "roles", permission_name: "roles_management" },
  { path: "registration", permission_name: "employee_management" },
  { path: "jobs", permission_name: "job_management" },
  { path: "blogs", permission_name: "blog_management" },
  { path: "news", permission_name: "news_management" },
  { path: "hooks", permission_name: "hooks_management" },
  { path: "contacts", permission_name: "contact_management" },
  { path: "quotes", permission_name: "quote_management" },
  { path: "candidates", permission_name: "job_management" },
  { path: "users", permission_name: "view_all_users" },
  { path: "gallery", permission_name: "gallery_management" },
  { path: "trainers", permission_name: "trainer_management" },
  { path: "candidate_testimonial", permission_name: "candidate_testimonial_management"},
];
