const projects = [
  {
    id: 1,
    image: "/images/services_images/1_Executive_Search.jpeg",
    altText: "Project Image",
    title: "Executive Search & Head Hunting",
    category: "Financial",
    linkText: "Read More",
    detailsUrl: "/services/1",
  },
  {
    id: 9,
    image: "/images/services_images/7_Employee_Wellness__Mental_Health.jpg",
    altText: "Project Image",
    title: "Employer of Record (EOR) & PEO",
    category: "Strategy",
    linkText: "Read More",
    detailsUrl: "/services/9",
  },
  {
    id: 5,
    image: "/images/services_images/5_HR_Management_and_consultant.jpg",
    altText: "Project Image",
    title: "HR & Management Consultancy",
    category: "Business",
    linkText: "Read More",
    detailsUrl: "/services/5",
  },
  {
    id: 10,
    image: "/images/services_images/11_BIDA_BEGA_Investment_Advisory.jpg",
    altText: "Project Image",
    title: "Payroll Management",
    category: "Strategy",
    linkText: "Read More",
    detailsUrl: "/services/10",
  },
  {
    id: 8,
    image: "/images/services_images/9_Employer_of_Record_EOR__PEO.jpg",
    altText: "Project Image",
    title: "Remote & Contract Staffing",
    category: "Resources",
    linkText: "Read More",
    detailsUrl: "/services/8",
  },
  {
    id: 12,
    image: "/images/services_images/Tailored_Training_Solutions.jpg",
    altText: "Project Image",
    title: "Tailored Training Solutions",
    category: "Strategy",
    linkText: "Read More",
    detailsUrl: "/services/12",
  },
  {
    id: 7,
    image: "/images/services_images/8_Remote__Contract_Staffing.jpg",
    altText: "Project Image",
    title: "Employee Wellness & Mental Health",
    category: "Startup",
    linkText: "Read More",
    detailsUrl: "/services/7",
  },
  {
    id: 4,
    image:
      "/images/services_images/6_Organization_Culture__Change_Management.jpg",
    altText: "Project Image",
    title: "Career Counselling & Placement",
    category: "Consultancy",
    linkText: "Read More",
    detailsUrl: "/services/4",
  },
  {
    id: 6,
    image: "/images/services_images/4_Career_Counseling.jpg",
    altText: "Project Image",
    title: "Organization Culture & Change Management",
    category: "Marketing",
    linkText: "Read More",
    detailsUrl: "/services/6",
  },
  {
    id: 2,
    image: "/images/services_images/2_Recruitment_process_outsourcing.png",
    altText: "Recruitment Process Outsourcing (RPO)",
    title: "Recruitment Process Outsourcing (RPO)",
    category: "Strategy",
    linkText: "Read More",
    detailsUrl: "/services/2",
  },

  {
    id: 3,
    image: "/images/services_images/3_Pre-Employment_Check.jpg",
    altText: "Project Image",
    title: "Pre-Employment Screening",
    category: "Consultancy",
    linkText: "Read More",
    detailsUrl: "/services/3",
  },
  {
    id: 13,
    image: "/images/services_images/14_Regulatory_Affairs_Consultancy.jpg",
    altText: "Project Image",
    title: "Labour Law Compliance Audit",
    category: "Strategy",
    linkText: "Read More",
    detailsUrl: "/services/13",
  },
  {
    id: 14,
    image: "/images/services_images/Regulatory_Affairs_Consultancy_resized.jpg",
    altText: "Project Image",
    title: "Regulatory Affairs Consultancy",
    category: "Strategy",
    linkText: "Read More",
    detailsUrl: "/services/14",
  },
  {
    id: 11,
    altText: "Project Image",
    image: "/images/services_images/10_Payroll_Management.jpg",
    title: "BIDA/BEZA/Investment Advisory",
    category: "Strategy",
    linkText: "Read More",
    detailsUrl: "/services/11",
  },
];

export { projects };
